### ISSUE TITLE
Question about test-std files

### ISSUE THREAD

**Issue by tsehsuan1102** [facebookresearch/simmc#42]
Hi, 
I am curious about the test-std files will be released on Sept 28.
Will you provide retrieval-candidate files and api call files?
Or just only provide one JSON file. ( _{domain}\_devtest_dials_teststd_format_public.json_)

Since we want to use the action information which is allowed at inference time mentioned in TASK_INPUTS.md. However, there is no annotated information in  _{furniture/fashion}\_devtest_dials_teststd_format_public.json_. How can we get the ground truth action?

We are using the preprocessing script in mm_action_predicition, but it is not able to process _{furniture/fashion}\_devtest_dials_teststd_format_public.json_.
Can you provide full test files before Sept. 28 that we can directly run on the baseline model?

**Comment by tsehsuan1102** [comment]
![圖片](https://user-images.githubusercontent.com/35379287/94338361-297fdc00-0024-11eb-8cb2-d0159b256458.png)

**Comment by seo-95** [comment]
Same issue here. Ground truth action is missing from the `test-std` draft file.  Additionally, I can't even find the item focus id for each turn, only partial information of the item is reported inside `visual_objects` and sometimes they are not sufficient.

```
                {
                    "domain": "fashion", 
                    "visual_objects": {
                        "OBJECT_2": {
                            "hemLength": [
                                "mini", 
                                "knee_length"
                            ], 
                            "pattern": [
                                "chevron", 
                                "animal"
                            ], 
                            "pos": "focus", 
                            "skirtStyle": [
                                "peplum", 
                                "a_line", 
                                "body_con", 
                                "loose", 
                                "fit_and_flare"
                            ], 
                            "embellishments": [
                                "pleated"
                            ], 
                            "type": "skirt"
                        }
                    }, 
                    "system_transcript": "Here is the skirt from Pedals & Gears. It retails for $124 and is rated at 3.96.", 
                    "turn_idx": 1, 
                    "belief_state": {}, 
                    "transcript": "sure"
                }
```

**Comment by shanemoon** [comment]
Hi all, sorry that this info was not included, we will look into this and release a new file soon.

Please do note though that we are providing {domain}_devtest_dials_teststd_format_public.json just as a guide before we release the future test-std set, and the results for Phase 1 should be reported on the {domain}_devtest_dials.json, released earlier.

**Comment by billkunghappy** [comment]
Hi, we're curious about the test-std file format.
Are there gonna be retrieval_candidates files and files contain API information for test-std? 
Since the team model entry deadline is getting closer, without the detailed format of the test-std files, we are afraid that our code may not be able to directly run on the test-std files( Which is able to directly run on the devtest set).

Are we allowed to modify preprocess code after **Sep.28** to run test-std ?(Only change some details to be able to successfully run it, without changing the models).

**Comment by satwikkottur** [comment]
Hello all, sorry for not including this information before.

For the `test-std` split, we will also release the corresponding API calls and retrieval candidates (public versions, excludes the last round on which evaluation is done) in the format of corresponding existing files.

In order to check for compatibility, we will now release `devtest` API calls and retrieval candidates in this format.

**Comment by billkunghappy** [comment]
Hello, there are still 2 questions about the submission.
First, for the Challenge Phase1, we should submit our devtest prediction files. In the Readme of the simmc Repo, it mentioned us to follow the instructions in the [Submission instruction](https://github.com/facebookresearch/simmc/blob/master/SUBMISSION_INSTRUCTIONS.md).
However there is no instruction about the submission of the devtest in **Submission instruction**. Should we email you the results of devtest? If so, which email address and what's the submission format?

Secondly, In the previous comment, @satwikkottur has said
`For the test-std split, we will also release the corresponding API calls and retrieval candidates (public versions, excludes the last round on which evaluation is done) in the format of corresponding existing files.`
What does the **excludes the last round on which evaluation is done** means?
I thought it means to exclude the last round API in each dialogue in the api calls file(exclude the last round of retrieval candidates is kind of weird, since we need those candidates to predict retrieval candidates scores)
But when I check into **fashion_devtest_dials_api_calls_teststd_format_public.json** and **furniture_devtest_dials_api_calls_teststd_format_public.json**, both files do include the last round API information correspond to the **fashion_devtest_dials_teststd_format_public.json** and **furniture_devtest_dials_teststd_format_public.json**

**Comment by satwikkottur** [comment]
Hello @billkunghappy,

Thanks for raising this concern.

Regarding the comment, your understanding is correct. 
(a) In the API calls file, the last round on which evaluation is to be performed will be excluded.
(b) For retrieval candidates, the last round will contain the retrieval candidates but will not contain the `gt_index` field that gives the index of the ground truth response.

With respect to the files, I just realized that the suffixes `public` and `private` got switched for API calls. While I will fix these later, please take a look at the wrongly named `furniture_devtest_dials_api_calls_teststd_format_private.json` (should be public) and corresponding file for `fashion`.

Hope this helps!

**Comment by seo-95** [comment]
Hi, I have 2 main questions concerning the `test-std` dataset regarding the `response_generation` task.

1. Since we can not use the information about the `action` and the `attributes` of the current turn (I thought it was a valid input as described in [TASK_INPUTS.md](https://github.com/facebookresearch/simmc/blob/master/TASK_INPUTS.md)), can we slightly modified the code (and not the model) in order to avoid taking them into account?

2. Why the dataset does not include the `item_id` annotation for each turn? In this way, we can access the `{domain}_metadata.json` file and retrieve all the info about the item. It seems to me to have only partial information inside the `visual_objects` that is not always compatible with the type of response given by the wizard.
For instance, in the example below, how can we generate a response containing the price if we do not have the information about the price?
```
                {
                    "domain": "fashion", 
                    "visual_objects": {
                        "OBJECT_2": {
                            "sleeveStyle": [
                                "sleeveless"
                            ], 
                            "pos": "focus", 
                            "dressStyle": [
                                "a_line", 
                                "tunic"
                            ], 
                            "waistStyle": [
                                "empire"
                            ], 
                            "embellishments": [
                                "mesh", 
                                "embroidered", 
                                "sequined"
                            ], 
                            "necklineStyle": [
                                "jewel_necklineStyle", 
                                "crew_neck", 
                                "illusion_necklineStyle", 
                                "yoke", 
                                "tank", 
                                "scoop_neck"
                            ], 
                            "jacketStyle": [
                                "fit_and_flare"
                            ], 
                            "type": "dress"
                        }
                    }, 
                    "system_transcript": "", 
                    "turn_idx": 5, 
                    "belief_state": {}, 
                    "transcript": "I could do an XS. But first I need to know the price - what is it?"
                }
```
In this other example instead, we do not have information about the item the wizard chooses to show.
```
                {
                    "domain": "fashion", 
                    "visual_objects": {}, 
                    "system_transcript": "", 
                    "turn_idx": 2, 
                    "belief_state": {}, 
                    "transcript": "Show me another coat, but one that 212 Localts more."
                }
```
During the first phase of the challenge, we had access to the `focus` item for each turn (contained in the `dials_api_calls` file) that allow us to correctly retrieve the item with which to condition the generation of the response.

**Comment by seo-95** [comment]
Hi, I have 2 questions raised from the `test-std` dataset release regarding the `response_generation` task.

1. Since the `action` and `attributes` annotations are not available for the current turn (differently from what was defined in [TASK_INPUTS.md](https://github.com/facebookresearch/simmc/blob/master/TASK_INPUTS.md)), are we able to slightly modify the code (not the model) to avoid using this information?

2. Whenever we encounter a potential `SearchMemory` or `SearchDatabase` in the `k-th` turn (the one on which the generation and the action prediction are evaluated) we do not have the annotation about the new `focus` item (during the first phase of the challenge it was included in the `dials_api` JSON file). Since the response of the wizard is conditioned on the item she/he is looking at, how can we generate such a response if we do not have information about the item?
An example here below (dialogue `1902`):
```
                {
                    "domain": "fashion", 
                    "visual_objects": {}, 
                    "system_transcript": "", 
                    "turn_idx": 2, 
                    "belief_state": {}, 
                    "transcript": "Show me another coat, but one that 212 Localts more."
                }
```

**Comment by satwikkottur** [comment]
Hello @seo-95 ,

Thanks for raising these two important concerns. We've updated the API calls file to include these two images for the last turn on which evaluation is performed. Of course, you're not allowed to use the ground truth API calls for subtask-1 but can use these for subtask-2 (as per the table). 

Apologies for the confusion earlier, hope this addresses your concerns.
