### ISSUE TITLE
KeyError caused by ~teststd_dials_retrieval_candidates_public.json

### ISSUE THREAD

**Issue by KimByoungjae** [facebookresearch/simmc#47]
![keyerror](https://user-images.githubusercontent.com/18690019/95158935-c3d7e080-07d7-11eb-8fed-ed8f6f25a604.png)
this error message occurred during preprocessing.

**Comment by satwikkottur** [comment]
Thanks for adding these details @KimByoungjae , the latest commit should fix this issue for `teststd` split.

For reference, the error stems from the fact that there are utterances in the retrieval candidates unseen when pooling all the system utterances due to dialogs being partially hidden. Feel free to reopen if issue persists.
