### ISSUE TITLE
How to get images

### ISSUE THREAD

**Issue by Mingxiao-Li** [facebookresearch/simmc#53]
I can't find the images. Does someone know how to get the imges?

**Comment by jind11** [comment]
I am also having this question

**Comment by skiingpacman** [comment]
Apologies for the confusion. Images weren't originally released as the SIMMC/DSTC-9 challenge focused on utilizing already extracted (actually known) information about the scenes rather than the extraction of signals from the raw multimodal signals. With the recent update to SIMMC-Furniture 1.2 (https://github.com/facebookresearch/simmc/pull/60) images for the Furniture (virtual reality) dataset are now available under simmc/data/simmc_furniture/.
